/* MONS catalog — stable images + hard reset for product cards/menu */
(function(){
'use strict';
const groups={
"Men’s Fashion":["Classic Cotton T-Shirt","Slim Fit Polo Shirt","Casual Linen Shirt","Regular Fit Jeans","Stretch Chino Pants","Lightweight Hoodie","Casual Bomber Jacket","Classic Denim Jacket","Formal Dress Shirt","Oxford Casual Shoes","Running Sneakers","Leather Belt","Minimal Wallet","Baseball Cap","Polarized Sunglasses","Cotton Socks Pack","Classic Wrist Watch","Travel Backpack","Crossbody Bag","Lightweight Joggers"],
"Women’s Fashion":["Ribbed T-Shirt","Elegant Blouse","Linen Summer Dress","Wide Leg Jeans","High Waist Trousers","Casual Cardigan","Lightweight Jacket","Denim Jacket","Maxi Dress","Comfort Sandals","Fashion Sneakers","Leather Handbag","Crossbody Purse","Classic Scarf","Fashion Sunglasses","Cotton Socks Pack","Minimal Watch","Everyday Tote Bag","Travel Backpack","Comfort Joggers"],
"Beauty":["Hydrating Face Cleanser","Vitamin C Face Serum","Daily Moisturizer","Hyaluronic Acid Serum","Gentle Face Toner","SPF 50 Sunscreen","Lip Balm Set","Matte Lipstick","Liquid Foundation","Makeup Brush Set","Mascara","Eyeliner Pen","Blush Palette","Eyeshadow Palette","Hair Shampoo","Hair Conditioner","Hair Brush","Body Lotion","Body Wash","Perfume Spray"],
"Home & Kitchen":["Nonstick Frying Pan","Stainless Steel Saucepan","Kitchen Knife Set","Bamboo Cutting Board","Digital Kitchen Scale","Electric Kettle","Coffee Maker","Insulated Travel Mug","Glass Food Container Set","Water Bottle","Dinner Plate Set","Ceramic Mug Set","Kitchen Storage Jars","Spice Rack Organizer","Dish Drying Rack","Microfiber Cleaning Kit","LED Desk Lamp","Storage Basket","Foldable Laundry Basket","Home Organizer Set"],
"Gadgets":["Smart Watch","Wireless Earbuds","Bluetooth Speaker","Power Bank","Wireless Charger","USB-C Hub","Mechanical Keyboard","Wireless Mouse","Phone Stand","Fast USB Charger","Multi Charging Cable","Portable Neck Fan","Mini Projector","Smart LED Bulb","Digital Alarm Clock","USB Desk Fan","Tablet Stand","Laptop Cooling Pad","Portable SSD Case","Smart Tracker Tag"],
"Pet Products":["Adjustable Dog Collar","Reflective Dog Leash","Dog Harness","Soft Pet Bed","Pet Feeding Bowl","Automatic Water Bowl","Interactive Dog Toy","Rubber Chew Toy","Dog Grooming Brush","Pet Nail Clipper","Cat Collar","Cat Scratching Mat","Cat Toy Ball Set","Cat Litter Scoop","Pet Travel Carrier","Pet Food Storage Box","Pet Bath Towel","Pet Waste Bag Holder","Pet Cooling Mat","Pet Blanket"],
"Electronics":["Smart LED TV","Bluetooth Soundbar","Noise Cancelling Headphones","Wireless Earbuds Pro","Smart Watch Pro","Android Tablet","Laptop Computer","USB Webcam","WiFi Router","Bluetooth Keyboard","Wireless Mouse Pro","Portable Power Bank","Fast Wall Charger","USB-C Dock","HDMI Adapter","Portable Bluetooth Speaker","Smart Home Camera","LED Monitor","External SSD","Gaming Controller"],
"Accessories":["Everyday Backpack","Leather Wallet","Card Holder","Travel Organizer","Key Holder","Minimal Sunglasses","Classic Cap","Leather Belt","Phone Case","Laptop Sleeve","Cable Organizer","Travel Pouch","Waterproof Pouch","Passport Holder","Luggage Tag","Reusable Shopping Bag","Compact Umbrella","Travel Pillow","Sports Water Bottle","Keychain"]
};
const colors={"Men’s Fashion":["#e7d4b5","#f2eadc"],"Women’s Fashion":["#e6c9cf","#f5e7e8"],Beauty:["#d8c5df","#f0e8f3"],"Home & Kitchen":["#d6c8a8","#f1ead8"],Gadgets:["#c5d4df","#e8f0f4"],"Pet Products":["#d5c7ad","#eee8dc"],Electronics:["#c7ccd4","#e9ecf0"],Accessories:["#d8cdbf","#eee9df"]};
const brand={"Men’s Fashion":"MONS Style","Women’s Fashion":"MONS Style",Beauty:"MONS Beauty","Home & Kitchen":"MONS Home",Gadgets:"MONS Gadgets","Pet Products":"MONS Pets",Electronics:"MONS Tech",Accessories:"MONS Accessory"};
const desc={"Men’s Fashion":"Quality-focused MONS fashion for practical everyday wear, with a clean modern fit.","Women’s Fashion":"Modern everyday style with a comfortable feel and versatile finish.",Beauty:"A practical everyday beauty essential designed for a simple routine.","Home & Kitchen":"A useful household essential designed for convenient everyday use.",Gadgets:"A smart everyday gadget for home, desk or travel use.","Pet Products":"A practical pet-care essential designed for comfort, play or grooming.",Electronics:"A modern electronic essential designed for convenient everyday use.",Accessories:"A simple, useful accessory designed for everyday carry."};
const icon={"Men’s Fashion":"shirt","Women’s Fashion":"dress",Beauty:"beauty","Home & Kitchen":"home",Gadgets:"gadget","Pet Products":"pet",Electronics:"tech",Accessories:"bag"};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function svg(name,cat,n){const [a,b]=colors[cat]||['#ddd','#f5f5f5'];const i=icon[cat]||'gadget';let art='';
if(i==='shirt'||i==='dress')art='<path d="M265 205l-55 42 35 35 25-17v190h140V265l25 17 35-35-55-42-38 22h-44z" fill="#fff" stroke="#111" stroke-width="7"/><path d="M320 205c8 22 52 22 60 0" fill="none" stroke="#111" stroke-width="7"/>';
else if(i==='beauty')art='<rect x="295" y="190" width="110" height="240" rx="28" fill="#fff" stroke="#111" stroke-width="7"/><rect x="320" y="150" width="60" height="48" rx="10" fill="#111"/><path d="M310 255h80" stroke="#111" stroke-width="7"/><circle cx="350" cy="340" r="28" fill="none" stroke="#111" stroke-width="7"/>';
else if(i==='home')art='<path d="M210 290l140-115 140 115v155H210z" fill="#fff" stroke="#111" stroke-width="7"/><path d="M320 445V335h60v110" fill="none" stroke="#111" stroke-width="7"/><path d="M250 290h200" stroke="#111" stroke-width="7"/>';
else if(i==='gadget'||i==='tech')art='<rect x="245" y="155" width="210" height="285" rx="30" fill="#fff" stroke="#111" stroke-width="7"/><circle cx="350" cy="405" r="10" fill="#111"/><rect x="285" y="205" width="130" height="160" rx="12" fill="'+b+'" stroke="#111" stroke-width="5"/><path d="M315 385h70" stroke="#111" stroke-width="7" stroke-linecap="round"/>';
else if(i==='pet')art='<circle cx="350" cy="335" r="82" fill="#fff" stroke="#111" stroke-width="7"/><circle cx="295" cy="260" r="27" fill="#fff" stroke="#111" stroke-width="7"/><circle cx="405" cy="260" r="27" fill="#fff" stroke="#111" stroke-width="7"/><circle cx="318" cy="325" r="10"/><circle cx="382" cy="325" r="10"/><path d="M330 365q20 20 40 0" fill="none" stroke="#111" stroke-width="7" stroke-linecap="round"/>';
else art='<rect x="235" y="205" width="230" height="170" rx="22" fill="#fff" stroke="#111" stroke-width="7"/><path d="M270 405h160" stroke="#111" stroke-width="12" stroke-linecap="round"/><path d="M320 375v30m60-30v30" stroke="#111" stroke-width="7"/>';
const text=esc(name).slice(0,28);return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 700"><defs><linearGradient id="g${n}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><rect width="700" height="700" rx="34" fill="url(#g${n})"/><circle cx="350" cy="320" r="190" fill="#ffffff66"/>${art}<text x="350" y="535" text-anchor="middle" font-family="Arial,sans-serif" font-size="27" font-weight="800" fill="#111">MONS</text><text x="350" y="575" text-anchor="middle" font-family="Arial,sans-serif" font-size="17" fill="#333">${text}</text><text x="350" y="615" text-anchor="middle" font-family="Arial,sans-serif" font-size="12" letter-spacing="3" fill="#777">EVERYDAY ESSENTIAL</text></svg>`);}
const products=[];let id=1;Object.keys(groups).forEach(cat=>groups[cat].forEach((name,i)=>{const image=svg(name,cat,id);products.push({id:id++,name,description:desc[cat],category:cat,brand:brand[cat],price:25+(i%10)*7+(cat.length%5)*3,image,gallery:[image,image,image,image],stock:'In Stock'});}));
window.MONS_PRODUCTS=products;window.dailyImage=p=>p.image;
function get(id){return products.find(p=>String(p.id)===String(id));}
function card(p){return `<article class="card"><div class="pic mons-view-pic" onclick="monsOpenProduct(${p.id})" role="button" tabindex="0" aria-label="View ${esc(p.name)}"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy"></div><span class="tag">${esc(p.brand)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="meta"><span>${p.stock}</span><span>${esc(p.category)}</span></div><div class="price-row"><span class="price">AED ${Number(p.price).toFixed(2)}</span><div class="product-actions"><button class="mini" type="button" onclick="event.stopPropagation();monsAdd(${p.id})">Add to Cart</button><button class="mini buy" type="button" onclick="event.stopPropagation();monsBuy(${p.id})">Buy Now</button></div></div></article>`;}
window.render=function(list,q=''){const g=document.getElementById('productGrid');if(!g)return;g.innerHTML=list.map(card).join('');const r=document.getElementById('resultText');if(r)r.textContent=q?`Showing ${list.length} products for “${q}”`:`Showing all ${list.length} products`;const e=document.getElementById('empty');if(e)e.style.display=list.length?'none':'block';};
window.search=function(q=''){q=String(q).toLowerCase().trim();window.render(products.filter(p=>(p.name+' '+p.description+' '+p.category+' '+p.brand).toLowerCase().includes(q)),q);};
window.monsOpenProduct=function(id){location.href='view.html?id='+encodeURIComponent(id);};
window.monsAdd=function(id){const p=get(id);if(!p)return;let c=JSON.parse(localStorage.getItem('monsCart')||'[]'),x=c.find(a=>String(a.id)===String(id));if(x)x.qty=Number(x.qty||1)+1;else c.push({id:p.id,name:p.name,price:Number(p.price),image:p.image,qty:1,category:p.category,description:p.description});localStorage.setItem('monsCart',JSON.stringify(c));const n=document.getElementById('cartCount');if(n)n.textContent=c.reduce((s,a)=>s+Number(a.qty||1),0);};
window.monsBuy=function(id){monsAdd(id);location.href='cart.html';};
const style=document.createElement('style');style.textContent=`
.products{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:18px!important;align-items:stretch!important}
.card{display:flex!important;flex-direction:column!important;min-width:0!important;width:auto!important;height:auto!important;overflow:hidden!important;background:#fff!important;border:1px solid #e4dfd5!important;border-radius:16px!important;padding:10px!important;position:relative!important}
.card *{box-sizing:border-box!important}
.pic{display:flex!important;position:relative!important;width:100%!important;height:250px!important;min-height:250px!important;flex:0 0 250px!important;align-items:center!important;justify-content:center!important;overflow:hidden!important;background:linear-gradient(145deg,#f7f4ed,#eee8dc)!important;border-radius:12px!important;cursor:pointer!important}
.pic img{display:block!important;width:100%!important;height:100%!important;max-width:none!important;object-fit:contain!important;margin:0!important;padding:0!important}
.tag{display:block!important;margin:12px 2px 0!important;min-height:12px!important;line-height:1.2!important}
.card h3{display:block!important;margin:6px 2px!important;min-height:36px!important;line-height:1.2!important;overflow-wrap:anywhere!important}
.card p{display:block!important;margin:0 2px!important;min-height:48px!important;line-height:1.45!important;overflow-wrap:anywhere!important}
.meta{display:flex!important;align-items:center!important;justify-content:space-between!important;margin:9px 2px 0!important;min-height:22px!important}
.price-row{display:flex!important;align-items:center!important;justify-content:space-between!important;margin:10px 2px 1px!important;gap:8px!important;min-height:40px!important}
.product-actions{display:flex!important;gap:5px!important;flex-shrink:0!important}
.mini{white-space:normal!important;line-height:1.15!important;min-height:36px!important}
.mobile-menu{display:none!important;position:fixed!important;right:18px!important;top:88px!important;width:min(330px,calc(100vw - 36px))!important;max-height:calc(100vh - 108px)!important;overflow:auto!important;background:#0c0c0c!important;color:#fff!important;border:1px solid #3d3d3d!important;border-radius:16px!important;padding:10px!important;z-index:9999!important;box-shadow:0 24px 70px #000b!important}
.mobile-menu.open{display:flex!important;flex-direction:column!important;gap:2px!important}
.mobile-menu a{display:flex!important;align-items:center!important;min-height:48px!important;width:100%!important;padding:12px 14px!important;border:0!important;border-radius:10px!important;color:#ddd!important;font-size:13px!important;font-weight:800!important;background:transparent!important}
.mobile-menu a:hover{background:#1b1b1b!important;color:#f5d27a!important}
@media(max-width:1150px){.products{grid-template-columns:repeat(3,minmax(0,1fr))!important}}
@media(max-width:760px){.products{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px!important}.pic{height:180px!important;min-height:180px!important;flex-basis:180px!important}.card{padding:8px!important}.card h3{font-size:13px!important}.card p{font-size:10px!important;min-height:44px!important}.price{font-size:13px!important}.mini{font-size:8px!important;padding:7px 6px!important}.mobile-menu{right:12px!important;top:72px!important;width:calc(100vw - 24px)!important}}
@media(max-width:480px){.products{grid-template-columns:1fr!important}.pic{height:235px!important;min-height:235px!important;flex-basis:235px!important}.card h3{font-size:15px!important}.card p{font-size:11px!important}}
`;document.head.appendChild(style);
function init(){window.render(products);const input=document.getElementById('searchInput');if(input&&!input.dataset.monsBound){input.dataset.monsBound='1';input.addEventListener('input',()=>window.search(input.value));}document.querySelectorAll('.cat').forEach(c=>{if(c.dataset.monsBound)return;c.dataset.monsBound='1';c.addEventListener('click',()=>{document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));c.classList.add('active');const q=c.dataset.q||'';window.render(q?products.filter(p=>p.category===q):products,q);});});const n=document.getElementById('cartCount');if(n){const c=JSON.parse(localStorage.getItem('monsCart')||'[]');n.textContent=c.reduce((s,a)=>s+Number(a.qty||1),0);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,20));else setTimeout(init,20);
})();