/* MONS catalog + web app install */
(function(){'use strict';
const groups={
"Men’s Fashion":["Classic Cotton T-Shirt","Slim Fit Polo Shirt","Casual Linen Shirt","Regular Fit Jeans","Stretch Chino Pants","Lightweight Hoodie","Bomber Jacket","Classic Denim Jacket","Formal Dress Shirt","Running Sneakers","Leather Belt","Baseball Cap"],
"Women’s Fashion":["Ribbed T-Shirt","Elegant Blouse","Linen Summer Dress","Wide Leg Jeans","High Waist Trousers","Casual Cardigan","Lightweight Jacket","Denim Jacket","Maxi Dress","Fashion Sneakers","Leather Handbag","Classic Scarf"],
"Beauty":["Hydrating Face Cleanser","Vitamin C Face Serum","Daily Moisturizer","Hyaluronic Acid Serum","Gentle Face Toner","SPF 50 Sunscreen","Lip Balm Set","Matte Lipstick","Makeup Brush Set","Mascara","Body Lotion","Perfume Spray"],
"Home & Kitchen":["Nonstick Frying Pan","Stainless Steel Saucepan","Kitchen Knife Set","Bamboo Cutting Board","Digital Kitchen Scale","Electric Kettle","Coffee Maker","Travel Mug","Glass Food Container Set","Water Bottle","Spice Rack Organizer","Storage Basket"],
"Gadgets":["Smart Watch","Wireless Earbuds","Bluetooth Speaker","Power Bank","Wireless Charger","USB-C Hub","Wireless Mouse","Phone Stand","Fast USB Charger","Portable Neck Fan","Mini Projector","Smart LED Bulb"],
"Pet Products":["Adjustable Dog Collar","Reflective Dog Leash","Dog Harness","Soft Pet Bed","Pet Feeding Bowl","Automatic Water Bowl","Interactive Dog Toy","Rubber Chew Toy","Dog Grooming Brush","Cat Collar","Pet Travel Carrier","Pet Cooling Mat"],
"Electronics":["Smart LED TV","Bluetooth Soundbar","Noise Cancelling Headphones","Wireless Earbuds Pro","Smart Watch Pro","Android Tablet","Laptop Computer","USB Webcam","WiFi Router","Bluetooth Keyboard","External SSD","Gaming Controller"],
"Accessories":["Everyday Backpack","Leather Wallet","Card Holder","Travel Organizer","Key Holder","Minimal Sunglasses","Classic Cap","Leather Belt","Phone Case","Laptop Sleeve","Travel Pouch","Passport Holder"]};
const brand={"Men’s Fashion":"MONS Style","Women’s Fashion":"MONS Style",Beauty:"MONS Beauty","Home & Kitchen":"MONS Home",Gadgets:"MONS Gadgets","Pet Products":"MONS Pets",Electronics:"MONS Tech",Accessories:"MONS Accessory"};
const desc={"Men’s Fashion":"Quality-focused MONS fashion for practical everyday wear.","Women’s Fashion":"Modern everyday style with a comfortable, versatile finish.",Beauty:"A practical everyday beauty essential for a simple routine.","Home & Kitchen":"A useful household essential for convenient everyday use.",Gadgets:"A smart everyday gadget for home, desk or travel.","Pet Products":"A practical pet-care essential for comfort, play or grooming.",Electronics:"A modern electronic essential for convenient everyday use.",Accessories:"A useful accessory designed for everyday carry."};
const colors={"Men’s Fashion":["#e7d4b5","#f2eadc"],"Women’s Fashion":["#e6c9cf","#f5e7e8"],Beauty:["#d8c5df","#f0e8f3"],"Home & Kitchen":["#d6c8a8","#f1ead8"],Gadgets:["#c5d4df","#e8f0f4"],"Pet Products":["#d5c7ad","#eee8dc"],Electronics:["#c7ccd4","#e9ecf0"],Accessories:["#d8cdbf","#eee9df"]};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function svg(name,cat,n){const [a,b]=colors[cat]||['#ddd','#f5f5f5'];let art='<rect x="245" y="155" width="210" height="285" rx="30" fill="#fff" stroke="#111" stroke-width="7"/><rect x="285" y="205" width="130" height="160" rx="12" fill="'+b+'" stroke="#111" stroke-width="5"/>';if(cat.includes('Fashion'))art='<path d="M265 205l-55 42 35 35 25-17v190h140V265l25 17 35-35-55-42-38 22h-44z" fill="#fff" stroke="#111" stroke-width="7"/>';if(cat==='Beauty')art='<rect x="295" y="190" width="110" height="240" rx="28" fill="#fff" stroke="#111" stroke-width="7"/><rect x="320" y="150" width="60" height="48" rx="10" fill="#111"/>';if(cat==='Home & Kitchen')art='<path d="M210 290l140-115 140 115v155H210z" fill="#fff" stroke="#111" stroke-width="7"/><path d="M320 445V335h60v110" fill="none" stroke="#111" stroke-width="7"/>';if(cat==='Pet Products')art='<circle cx="350" cy="335" r="82" fill="#fff" stroke="#111" stroke-width="7"/><circle cx="295" cy="260" r="27" fill="#fff" stroke="#111" stroke-width="7"/><circle cx="405" cy="260" r="27" fill="#fff" stroke="#111" stroke-width="7"/>';const text=esc(name).slice(0,28);return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 700"><defs><linearGradient id="g${n}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><rect width="700" height="700" rx="34" fill="url(#g${n})"/><circle cx="350" cy="320" r="190" fill="#ffffff66"/>${art}<text x="350" y="535" text-anchor="middle" font-family="Arial" font-size="27" font-weight="800" fill="#111">MONS</text><text x="350" y="575" text-anchor="middle" font-family="Arial" font-size="17" fill="#333">${text}</text></svg>`);}
const products=[];let id=1;Object.keys(groups).forEach(cat=>groups[cat].forEach((name,i)=>{const image=svg(name,cat,id);products.push({id:id++,name,description:desc[cat],category:cat,brand:brand[cat],price:25+(i%10)*7+(cat.length%5)*3,image,gallery:[image,image,image,image],stock:'In Stock'});}));
window.MONS_PRODUCTS=products;window.dailyImage=p=>p.image;
function get(id){return products.find(p=>String(p.id)===String(id));}
function card(p){return `<article class="card"><div class="pic mons-view-pic" onclick="monsOpenProduct(${p.id})" role="button" tabindex="0"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy"></div><span class="tag">${esc(p.brand)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="meta"><span>${p.stock}</span><span>${esc(p.category)}</span></div><div class="price-row"><span class="price">AED ${Number(p.price).toFixed(2)}</span><div class="product-actions"><button class="mini" type="button" onclick="event.stopPropagation();monsAdd(${p.id})">Add to Cart</button><button class="mini buy" type="button" onclick="event.stopPropagation();monsBuy(${p.id})">Buy Now</button></div></div></article>`;}
window.render=function(list,q=''){const g=document.getElementById('productGrid');if(!g)return;g.innerHTML=list.map(card).join('');const r=document.getElementById('resultText');if(r)r.textContent=q?`Showing ${list.length} products for “${q}”`:`Showing all ${list.length} products`;const e=document.getElementById('empty');if(e)e.style.display=list.length?'none':'block';};
window.search=function(q=''){q=String(q).toLowerCase().trim();window.render(products.filter(p=>(p.name+' '+p.description+' '+p.category+' '+p.brand).toLowerCase().includes(q)),q);};
window.monsOpenProduct=function(id){location.href='view.html?id='+encodeURIComponent(id);};
window.monsAdd=function(id){const p=get(id);if(!p)return;let c=JSON.parse(localStorage.getItem('monsCart')||'[]'),x=c.find(a=>String(a.id)===String(id));if(x)x.qty=Number(x.qty||1)+1;else c.push({id:p.id,name:p.name,price:Number(p.price),image:p.image,qty:1,category:p.category,description:p.description});localStorage.setItem('monsCart',JSON.stringify(c));const n=document.getElementById('cartCount');if(n)n.textContent=c.reduce((s,a)=>s+Number(a.qty||1),0);};
window.monsBuy=function(id){monsAdd(id);location.href='cart.html';};
function addAppUI(){if(document.getElementById('monsAppLink'))return;const a=document.createElement('a');a.id='monsAppLink';a.href='./';a.textContent='MONS APP';a.setAttribute('aria-label','Open MONS App');a.style.cssText='position:fixed;right:18px;bottom:18px;z-index:99999;background:linear-gradient(135deg,#f5d27a,#b98a36);color:#111;border:1px solid #111;border-radius:999px;padding:12px 17px;font:900 11px Arial;letter-spacing:.8px;box-shadow:0 10px 30px #0005';document.body.appendChild(a);if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});const m=document.createElement('link');m.rel='manifest';m.href='./manifest.webmanifest';document.head.appendChild(m);}
const style=document.createElement('style');style.textContent='.products{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:18px!important}.card{display:flex!important;flex-direction:column!important;min-width:0!important}.pic{height:250px!important;min-height:250px!important;flex:0 0 250px!important}.pic img{width:100%!important;height:100%!important;object-fit:contain!important}.card h3{min-height:36px}.card p{min-height:48px}.price-row{margin-top:auto;padding-top:10px}.mobile-menu{z-index:9999!important}@media(max-width:1150px){.products{grid-template-columns:repeat(3,minmax(0,1fr))!important}}@media(max-width:760px){.products{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px!important}.pic{height:180px!important;min-height:180px!important;flex-basis:180px!important}}@media(max-width:480px){.products{grid-template-columns:1fr!important}.pic{height:235px!important;min-height:235px!important;flex-basis:235px!important}}';document.head.appendChild(style);
function init(){window.render(products);const n=document.getElementById('cartCount');if(n){const c=JSON.parse(localStorage.getItem('monsCart')||'[]');n.textContent=c.reduce((s,a)=>s+Number(a.qty||1),0);}addAppUI();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,20));else setTimeout(init,20);
})();